### PR TITLE
Stitch fields

### PR DESCRIPTION
**Pull request by jo-pol**
Objective
---------

* #49 color code
* #100 Shorthand for stitch assignments
* Override default color

Progress
--------

* [x] Parse the input field.
* [x] Apply new default colors in all pair diagrams.
* [x] Shorthand assignments for first pair diagram.
  So far to be tested with docs/index.html in [stitch-fields.zip](https://github.com/d-bl/GroundForge/archive/stitch-fields.zip)
* [ ] Shorthand assignments for level 2/3 diagrams.
* [ ] Override colors.
* [ ] When all above is implemented: adjust [wiki/stitches] and [wiki/color-code].
  The latter should use plain English for the rules at the bottom of [stitches].
  Examples for both are available in [StitchesSpec].

[StitchesSpec]: https://github.com/d-bl/GroundForge/blob/stitch-fields/src/test/scala/dibl/StitchesSpec.scala#L23
[stitches]: https://github.com/d-bl/GroundForge/blob/stitch-fields/src/main/scala/dibl/Stitches.scala
[wiki/stitches]: https://github.com/d-bl/GroundForge/wiki/Choose-Stitches
[wiki/color-code]: https://github.com/d-bl/GroundForge/wiki/Color-Code

### CODE REVIEW

**Comment by jo-pol** [comment]
@MAETempels 

Please first _read_ the intro of the pull request and _review_ the [wiki/color-code] page.

Would you mind to propose more examples (alias tests)? For that purpose you can edit the file [StitchesSpec] following the pull request procedure starting at [step 2]. You might also want to propose different rules for the default colors. Once it all works, it would be good to have one or two diagrams for the wiki page that demonstrate all colors and some twist marks.

[StitchesSpec]: https://github.com/d-bl/GroundForge/blob/stitch-fields/src/test/scala/dibl/StitchesSpec.scala#L23
[step 2]: https://help.github.com/articles/editing-files-in-another-user-s-repository/
[wiki/color-code]: https://github.com/d-bl/GroundForge/wiki/Color-Code

**Comment by jo-pol** [comment]
A sneak preview of a new form
=============================

Whenever I push another commit to this issue you can [download] the latest version and try `docs/_includes/tiles-form.html`

@veronika @MAETempels

The form is born out of the need for tiling variations with another shift value than a half brick. At last the pennies dropped extending the current [stitches] form with more functionality. The new form is not yet fully functional but Marian, you might like to play with it and prefer it over the diagram link on the main page. 

A seasoned JavaScript developer might be able to update the prototype while you type in the definition field. For now you have to use the tab-key to leave the field or click somewhere else on the page to update the prototype. Once implemented, the go button will use #100 for the new tiling capabilities. For that purpose you can make the stitches field on the main page span multiple lines.

Not sure the form will some day get integrated in the main page. Anyway I would appreciate feedback and advice from both of you. For example I'm in doubt about the 'prototype' caption. Veronika, when you read the [help intro] you might understand why Marian minted these [diagrams] 'draft pricking', so any suggestion?

[help intro]: https://d-bl.github.io/GroundForge/help
[stitches]: https://d-bl.github.io/GroundForge/help/Choose-Stitches
[download]: https://github.com/d-bl/GroundForge/archive/stitch-fields.zip
[diagrams]: https://d-bl.github.io/GroundForge/sheet.html?img=376&patch=B-C-%20---5%20C-B-%20-5--;checker&patch=5831%20-4-7;checker&patch=68%20-4;checker&patch=-4-7%205---%20-C-B%203158;bricks&patch=5-O-E-%20-E-5-O%205-O-E-;bricks

**Comment by jo-pol** [comment]
Thinking load: To implement the go button I need to create a checker-matrix and thus need the [lcm] of shift value and corresponding matrix dimension. Matrix dimensions span 1-8, shift spans 0-7. A simple solution would be a table with 8x8 cells with the lcm values. Hm, the shift should get a sign, to reduce the size of the checker matrix.


  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
1 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
2 | 2 | 2 | 6 | 4 | 10 | 6 | 14 | 8
3 | 3 | 6 | 3 | 12 | 15 | 6 | 21 | 24
4 | 4 | 2 | 12 | 4 | 20 | 12 | 28 | 8




[lcm]: https://en.wikipedia.org/wiki/Least_common_multiple#Computing_the_least_common_multiple

**Comment by MAETempels** [comment]
**NICE!!** Like it indeed!!
If this works nicely it could replace the main form.

If you allow a shift 0, then you have a checkers diagram?

Some first remarks,

- Of course,  I tried first a 9 collumns matrix. Then realized the maximum of 8. 

- At  first, I did not see where the small line (in the green oval) was coming from. Then realized it is 2 long. The "empty cirkels" are a bit confusing at first glance. Of course the line nicely disappeared when applying the shift needed.

- The stitches field might be clearer if the "-" from the matrix definition are incorporated. It is easier to work with than searching for the ID's. (And it might work on tablets too).

- Not sure what is intended with "variants". It seems not to do anything.

- The "go" button send me nicely to the main form. However, the matrix is not yet working. (Of course not with the matrix I used, but also not with the example matrix (from the mail).)
(I noticed that the example provided is multiple rows.) 
There is a footside shift down of 2, why?

- I like the draft-diagram (prototype).  It saves clicking on the [diagram] button. However, I would drop the cheat-sheet and display the draft-diagram just as clear lines. See also second remark.
I do not mind to click somewhere to update this picture. Would be very "nervously" if it changed with every letter put in the matrix-field.

image

Another example
image

The following example: I would have thought, it to be a shift of 3 collumns (to the right). Apparently, the move is to the left. Might be nice to put this information on the form. Or, indeed, allow -3.
image

**Comment by jo-pol** [comment]
* Shift zero is indeed a checker pattern. A shift of half the matrix width is a brick pattern.
* So far only the checker and bricks tiling are supported, as I wrote: not yet fully functional. For that reason the example from the mail (5,1,8,4,8,-,- shift by 2 rows) shows a `notYetImplemented` in the go-link where the tiling (checker/bricks) would go for existing patterns. But at least the prototype can show you it is a valid pattern.
* A valid pattern will always have at least one stitch in each row or column. That will make the positions of the stitch fields clearer. Also long lines will only go across empty circles. You will see when trying any of the get-started examples.
* Variants are indeed not yet implemented. See the form on help/Choose-stitches where you can choose larger matrices. It is meant to allow different stitches for every other spider or whatever feature appears in a pattern. Non-1 values require multiplying the stitch form, but what to do with shifted tiles? Multiply complete tiles? Or for example in case of the current bricks show a checker tile?
* The shift on the main page is required to match the stitch positions in the form with ID's in the generated pattern. If that indeed solves all ID problems, I can close #96
* "_Apparently, the move is to the left. Might be nice to put this information on the form._" not sure it would clutter the form too much. This one has to sink into my brain.
* I guessed the cheat-sheet and numbered circles in the prototype can be helpful when seriously designing/debugging new patterns. I'm not making that decision right now. You could play with it in your local copy or even the browser debugger. In the HTML you will find SVG structures like

      <g id="g9" ...>
          <path .../>
          <text ...>9</text>
          <path ..."...marker-end:url(#Arrow1Mend)"/>
          <path ..."...;marker-end:url(#Arrow1Mend)" />
      </g>

   For example drop the arrows, change the stroke width, or make "g-" (what you called empty-circle) almost fully transparent: `opacity:0.3;` in a style attribute. Dropping the circle and text however will leave gaps.

**Comment by MAETempels** [comment]
- I have examples where the ID's are shifted both in rows and in collumns. In these examples: 2 collums: all matrices starting with C.  Rows shift also 2: starting with 3 in the diagram.
See
5---, -C-B, 5-5-, -5-5, --5-, -B-C, 5-5-, -5-5 (Checkers) Starts with C3.
or bricks: 5-5-, -5--, B-C-, -5-5 starts with A3.
or bricks: 5---, -C-B, 5-5-, -5-5 starts with A3
(all the same)

--B-C---, -E-5-O-K, 5-----5-, -------5 bricks: G3 seems to be in the upper-left corner. Also seems to shift 2 both rows & collumns.
(I have more examples. Might want to check all matrices I made.)

- If this new form is going to be the new main-page, then the ID's are no longer important. As long as it is clear which stitch-field belongs to which "point" of the proto-pricking. Also, the difference between bricks and checkers is no longer nessecarilly - as a move of 0 is a checkers-pattern. 

- The stitch-fields are rather big. 

- The blocks may be moved horizontally, or vertically. I have a slight feeling that this is not the same pattern. Have to work this out.
**abc**abc  ---   **abc**ghi
**def**def ---     **def**abc
**ghi**ghi ---     **ghi**def
bcabca ---          abcghi
efdefd ---           defabc
highig  ---          ghidef

**Comment by MAETempels** [comment]
-After some sleep: a new mainpage will give lots issues with existing examples. 

- Refrase puzzle: if a diagram has a horizontal brick pattern, does it also have a vertical? Answer: NO
See 5831, -4-7

- more thoughts later.

**Comment by jo-pol** [comment]
I suppose you meant shift 2 columns for `5831, -4-7` as it also works as a checker pattern, it works with shifted by 2 rows for `58,-4,31,-7`.

Generalized: a brick pattern `ab`  (with the same dimensions for `a` and `b` in number of stitches) can be turned into a checker pattern `ab,ba` from which you can extract the vertical bricks `a,b` or `b,a`. For different width of `a` and `b` I don't have yet a similar reasoning at hand, their checker dimensions can become quite large, see https://github.com/d-bl/GroundForge/pull/106#issuecomment-343654249

**Comment by jo-pol** [comment]
Indeed I see a problem for unequal dimensions. In the following example with a horizontal tile of 2 rows by 3 columns, the smallest vertical tile I can find is 6 rows by 2 columns. A fun thing, though I don't see see a use case, are overlapping tiles. The table [above](https://github.com/d-bl/GroundForge/pull/106#issuecomment-343654249) for checker sizes also makes no sense. Here we have a checker matrix of 6 rows by 6 columns.

  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
a | b | c | a | b | c | a | b | c | a | b | c |   |   |   |  
d | e | f | d | e | f | d | e | f | d | e | f |   |   |   |  
  | a | b | c | a | b | c | a | b | c | a | b | c |   |   |  
  | d | e | f | d | e | f | d | e | f | d | e | f |   |   |  
  |   | a | b | c | a | b | c | a | b | c | a | b | c |   |  
  |   | d | e | f | d | e | f | d | e | f | d | e | f |   |  
  |   |   | a | b | c | a | b | c | a | b | c | a | b | c |  
  |   |   | d | e | f | d | e | f | d | e | f | d | e | f |  
  |   |   |   | a | b | c | a | b | c | a | b | c | a | b | c
  |   |   |   | d | e | f | d | e | f | d | e | f | d | e | f

Layout hint: just copy-paste from a spreadsheet like Excel, the first line is interpreted as a header row, it can be empty.

**Comment by MAETempels** [comment]
I was not quite awake when I gave the example for vertical - horizontal bricks.
Please look at this picture:

bloks

Given: a pattern with horizontal blocks.
Let:
w = width of block
h = height of block
m = move / shift of block to generate the pattern.

let r = number of blocks needed vertically to generate the pattern.
Then: r x m eq 0 (mod w). take the smallest r   (and r <= w)

The corresponding Vertical block has 
width = m
height = h x r
shift down = h
s = number of blocks needed horizontally: s x h eq 0 (mod hxr)
then: width of total = m x s.
(note: we might have to allow fractions for s and r. I'll work this out later.)

For the corresponding Checkers matrix the following holds:
width = w (! given the horizontal block)
height = h x r

**Comment by jo-pol** [comment]
* big fields: The fields adapt their width to the available space. Within a help page, on a mobile or with more columns that would be less.
* empty fields: I hide the not used fields. If the same column doesn't have a field on another row, the complete column disappears. That is nice for rows and columns that are not use at all because the matrix has less than the (arbitrary) maximum of 8. But I see that can be a problem for shifted matrices, so I need a different strategy.

**Comment by MAETempels** [comment]
I have made a doc about the horizontal and vertical bricks, with neater pictures. With a small comment on the "fractions" mentioned.
[bricks.pdf](https://github.com/d-bl/GroundForge/files/1475516/bricks.pdf)

**Comment by MAETempels** [comment]
One more word.

Suppose we have a horizontal brick with width w=9, and a shift of m=3, height h.

As discussed before:
we need r:  r x 3 eq 0 (mod 9) --> r = 3
whereas: lcm(3,9) = 9.

A much smaller value!

**Comment by jo-pol** [comment]
Closing the pull request as is has broken links and left the original subject

**Pull request closed without merging**
